name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  1-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

  2-job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "This is a variable"

    steps:
      - name: Show environment variable
        run: echo "The value of MY_VARIABLE is: ${{ env.MY_VARIABLE }}"
