name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "This is a variable"
      
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Show environment variable
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"
