name: My First GitHub Action

on:
  push:
    branches:
      - main
  
permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "This is a variable"
      
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Show coverage files (debug)
        run: ls -R coverage

      - name: Run tests & coverage
        run: npx jest

      - name: Upload coverage to Coveralls
        run: npx coveralls < coverage/lcov.info
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}


      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Show environment variable
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"

      - name: Show secret (masked)
        run: echo "The secret is ${{ secrets.MY_SECRET }}"

      - name: Create hello.txt
        run: echo "Hello world" > hello.txt

      - name: Show content of hello.txt
        run: cat hello.txt
        
  second-job:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Say something
        run: echo "Second job running"
